spring:
  application:
    name: prometheus-test

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    enable:
      all: true
    endpoint:
      prometheus:
        enabled: true